### ISSUE TITLE
Plugin fails to load after reboot

### ISSUE THREAD

**Issue by dnasini** [VRGhost/OctoPrint-PSUControl-Meross#8]
After installation, Octoprint pops up a message saying "Install _Unknown_" and the green flag that says "everything is correct" and asks for reboot. After reboot, the PSU Control - Meross plugin is not listed into the installed plugins. Having a look to the logs, Octoprint reports those errors

2022-04-27 17:49:01,676 - octoprint.startup - INFO - ******************************************************************************
2022-04-27 17:49:01,678 - octoprint.startup - INFO - Starting OctoPrint 1.7.3
2022-04-27 17:49:01,678 - octoprint.startup - INFO - ******************************************************************************
2022-04-27 17:49:01,963 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2022-04-27 17:49:02,000 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2022-04-27 17:49:02,000 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2022-04-27 17:49:02,000 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2022-04-27 17:49:02,006 - octoprint.startup - INFO - Blacklist processing done, adding 3 blacklisted plugin versions: roomtemp (any), GcodeEditor (>=0.1.1,<=0.2.8), gcodeleveling (>=0.1.0,<=0.1.1)
2022-04-27 17:49:02,043 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
**_2022-04-27 17:49:03,172 - octoprint.plugin.core - ERROR - Error loading plugin psucontrol_meross_**
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1291, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 68, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_meross/__init__.py", line 11, in <module>
    from .plugin import PSUControlMeross
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_meross/plugin.py", line 6, in <module>
    from . import meross_client
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_meross/meross_client.py", line 17, in <module>
    from meross_iot.model.exception import (
**_ImportError: cannot import name 'MqttError' from 'meross_iot.model.exception' (/home/pi/oprint/lib/python3.7/site-packages/meross_iot/model/exception.py)_**
.......

**Comment by IljaOrlovs** [comment]
Hello,
It appears that something went wrong with the package installation. This _probably_ has nothing to do with me.

Are you still able to replicate the issue? (Considering that the ticket had been opened a while ago)

**Comment by dnasini** [comment]
Hi, well it could be. Anyway, at that time I tried more than once to reinstall the pluging with same result. After your reply, I noticed a new version is available. I just installed the last one and now sounds it works. No strange message at the end of the install phase and after reboot I see it listed in the plugins list. I'll test it later and, just in case, I'll let you know.

**Comment by IljaOrlovs** [comment]
Please do tell if it doesn't work - I can give you pointers to how fix this error if you're comfortable with SSH'ing to the device.

**Comment by dnasini** [comment]
Hi, it tooks a while to config and test it but it sounds to work fine. 

Thank you
